name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: GuySartorelli/gha-ci/.github/workflows/ci.yml@1
    with:
      # Turn phpcoverage off because it causes a segfault
      phpcoverage_force_off: true
